// two formats on purpose:
//
//   yaml -- engine-facing, and RESOLVED. the tool solves; the engine composes
//           mechanically, so the ref graph is flattened here into concrete
//           world frames and rust never walks a ref. snake_case to match
//           serde, angles in degrees.
//
//   json -- the tool's own round-trip: the authoring graph, refs intact.

import { resolveFrames, boneKey } from './skeleton.js';
import { bakeAnimation, solveOffset } from './bake.js';
import { loopPeriod } from './animation.js';
import { fmt, wrapDeg } from './math.js';
import { normalizeDoc, SCHEMA } from './store.js';

const refYaml = (ref) => {
  if (ref?.art != null) return `{ art: ${ref.art}, anchor: ${JSON.stringify(ref.anchor)} }`;
  if (ref?.bone != null) return `{ bone: ${ref.bone}, end: ${ref.end ?? 'root'} }`;
  return 'null';
};

export function exportYaml(doc, artPaths = null) {
  const standing = solveOffset(doc);
  // the raw rest configuration: constraints are an authoring aid, and baking
  // their result into it would make it un-editable downstream
  const { frames } = resolveFrames(doc, { posed: false, constraints: false });
  const out = [
    '# tauroid skeleton -- generated by tools/rigger',
    '# resolved configuration. positions are world, angles are degrees.',
    '# a bone may have length zero: a frame with a direction and nothing drawn',
    '# along it (grip, socket, mount, ik target). still a bone like any other --',
    '# there is one entity, and no separate kind to branch on.',
    '#',
    '# a bone poses at rest + pose_angle, and animation deltas add to that.',
    '# only a constraint replaces any of it, rather than adding.',
    '#',
    '# solve_offset and animation keyframe deltas are both triples ordered',
    '# [angle, offset_x, offset_y]. keyframe deltas are measured FROM REST.',
    '# frames between keys interpolate linearly; animations that overlap on a',
    '# bone add, so composition order does not matter. a forward loop wraps from',
    '# its last key to frame 0; back-and-forth reverses at its last frame.',
    '#',
    '# each animation carries BOTH: `keyframes` is what was authored, `baked` is',
    '# the same motion with constraints already solved, split per bone per',
    '# channel as [frame, value, d|t] -- d designed, t generated to keep a',
    '# linear tween faithful. Play `baked` and no solver is needed.',
    'bones:',
  ];
  if (!doc.bones.length) out[out.length - 1] = 'bones: []';

  for (const b of doc.bones) {
    const f = frames.get(boneKey(b.id, 'root'));
    if (!f) continue;
    out.push(`  - id: ${b.id}`);
    out.push(`    name: ${JSON.stringify(b.name)}`);
    out.push(`    parent: ${b.ref?.bone ?? 'null'}`);
    if (b.ref?.bone) out.push(`    parent_end: ${b.ref.end ?? 'root'}`);
    out.push(`    pos: [${fmt(f.pos.x, 3)}, ${fmt(f.pos.y, 3)}]`);
    out.push(`    angle: ${fmt(wrapDeg(f.angle), 3)}`);
    out.push(`    length: ${fmt(b.length, 3)}`);
    // The pose delta is part of the rig, not a preview aid: the model is
    // rest + pose + animation. It lives HERE rather than inside the baked
    // animations because each animation is baked in isolation -- carrying it
    // there would make the engine add it once per active animation.
    if (Math.abs(b.poseAngle ?? 0) > 1e-9) out.push(`    pose_angle: ${fmt(wrapDeg(b.poseAngle), 3)}`);
    // What the constraints do with nothing animating. A CONSTANT, so it lives
    // here and is added once -- carrying it inside each animation is what made
    // two active lanes apply it twice.
    const z = standing[b.id];
    if (z) out.push(`    solve_offset: [${fmt(z.angle, 3)}, ${fmt(z.offsetX, 3)}, ${fmt(z.offsetY, 3)}]`);

    // The authoring constraint, emitted for completeness. The baked animation
    // below already has the solve applied, so an engine that only tweens can
    // ignore this entirely -- it is here so nothing about the rig is hidden,
    // and so a runtime-driven target (an aim that follows the player) can be
    // re-solved live if that is ever wanted.
    const c = b.constraint;
    if (c) {
      out.push('    constraint:');
      out.push(`      kind: ${c.kind}`);
      out.push(`      target: ${refYaml(c.target)}`);
      if (c.kind === 'reach') out.push(`      bend: ${c.bend >= 0 ? 1 : -1}`);
      if (c.kind === 'match') {
        out.push(`      space: ${c.space ?? 'local'}`);
        out.push(`      take: [${['x', 'y', 'theta'].filter((k) => c.take?.[k]).join(', ')}]`);
        out.push(`      offset: [${fmt(c.offset?.x ?? 0, 3)}, ${fmt(c.offset?.y ?? 0, 3)}, ${fmt(c.offset?.theta ?? 0, 3)}]`);
      }
    }
  }

  // art is emitted in PAINT order, back to front, so the engine draws the list
  // as it reads it -- no sorting, no z field to get backwards. that is the
  // reverse of the tool's list, where index 0 is nearest the viewer.
  //
  // the file is referenced by name, not inlined: the engine loads its own
  // assets, and two items sharing a file should cost one load and two draws.
  const art = [...(doc.art ?? [])].reverse();
  out.push(art.length ? 'art:' : 'art: []');
  for (const a of art) {
    out.push(`  - id: ${a.id}`);
    out.push(`    name: ${JSON.stringify(a.name)}`);
    // the bundle may rename a file to keep two items with different anchors
    // apart, so reference what was actually written
    out.push(`    svg: ${JSON.stringify(artPaths?.get(a.id) ?? a.filename)}`);
    // where the art hangs: a bone (root or tip), or another art's anchor
    if (a.ref?.art != null) {
      out.push(`    parent_art: ${a.ref.art}`);
      out.push(`    parent_anchor: ${JSON.stringify(a.ref.anchor)}`);
    } else {
      out.push(`    parent: ${a.ref?.bone ?? 'null'}`);
      if (a.ref?.bone) out.push(`    parent_end: ${a.ref.end ?? 'root'}`);
    }
    out.push(`    offset: [${fmt(a.offset.x, 3)}, ${fmt(a.offset.y, 3)}]`);
    out.push(`    angle: ${fmt(wrapDeg(a.angle), 3)}`);
    if (a.scale !== 1) out.push(`    scale: ${fmt(a.scale, 4)}`);
    if (!a.visible) out.push('    visible: false');
  }

  const anims = doc.animations ?? [];
  out.push(anims.length ? 'animations:' : 'animations: []');
  for (const anim of anims) {
    out.push(`  - id: ${anim.id}`);
    out.push(`    name: ${JSON.stringify(anim.name)}`);
    out.push(`    type: ${anim.type}`);
    out.push(`    length: ${anim.length}`);
    out.push(anim.keyframes.length ? '    keyframes:' : '    keyframes: []');
    for (const kf of anim.keyframes) {
      out.push(`      - frame: ${kf.frame}`);
      const entries = Object.entries(kf.deltas);
      if (entries.length) {
        out.push('        deltas:');
        for (const [boneId, d] of entries) {
          out.push(`          ${boneId}: [${fmt(d.angle, 3)}, ${fmt(d.offsetX, 3)}, ${fmt(d.offsetY, 3)}]`);
        }
      } else {
        out.push('        deltas: {}');
      }
    }

    // BAKED: the solve already applied, as per-channel keys an engine can
    // simply tween. Channels are independent, so a bone whose angle is pinned
    // by a theta match keeps two keys while its position gets as many as the
    // arc needs. `d` marks a key you drew, `t` one computed to keep the tween
    // honest -- the solve is not linear, so the authored keys alone are not
    // enough to reproduce it.
    const baked = bakeAnimation(doc, anim);
    const ids = Object.keys(baked);
    out.push(ids.length ? '    baked:' : '    baked: {}');
    for (const id of ids) {
      out.push(`      ${id}:`);
      for (const [ch, keys] of Object.entries(baked[id])) {
        const snake = ch === 'offsetX' ? 'offset_x' : ch === 'offsetY' ? 'offset_y' : ch;
        const cells = keys.map((k) => `[${k.frame}, ${fmt(k.value, 3)}, ${k.designed ? 'd' : 't'}]`);
        out.push(`        ${snake}: [${cells.join(', ')}]`);
      }
    }
  }

  return out.join('\n') + '\n';
}

// stamp the schema, exactly as persisting to localStorage does. without it the
// file fails its own version check on the way back in.
export const exportJson = (doc) =>
  JSON.stringify({ ...doc, version: SCHEMA }, null, 2);

export function importJson(text) {
  const raw = JSON.parse(text);
  if (!Array.isArray(raw?.bones)) throw new Error('not a rigger document');
  // same gate as localStorage: a file from an older schema is rejected loudly
  // rather than crashing the resolver on a missing field
  // normalizeDoc migrates anything from MIN_SCHEMA up, and throws a
  // SchemaError with a reason for anything it genuinely cannot bring forward
  const doc = normalizeDoc(raw);
  if (!doc) throw new Error('not a rigger document');
  return doc;
}

export function download(filename, text, type = 'text/plain') {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.append(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
