// two formats on purpose:
//
//   yaml -- engine-facing, and RESOLVED. the tool solves; the engine composes
//           mechanically, so the ref graph is flattened here into concrete
//           world frames and rust never walks a ref. snake_case to match
//           serde, angles in degrees.
//
//   json -- the tool's own round-trip: the authoring graph, refs intact.

import { resolveFrames, boneKey, isPoint } from './skeleton.js';
import { fmt, wrapDeg } from './math.js';
import { normalizeDoc, SCHEMA } from './store.js';

export function exportYaml(doc, artPaths = null) {
  // the raw bind pose: constraints are an authoring aid, and baking their
  // result into the rest skeleton would make it un-editable downstream
  const { frames } = resolveFrames(doc, { posed: false, constraints: false });
  const out = [
    '# tauroid skeleton -- generated by tools/rigger',
    '# resolved rest pose. positions are world, angles are degrees.',
    '# a zero-length bone is an attachment point: a frame with a direction',
    '# and no extent (grip, socket, mount, ik target).',
    '#',
    '# animation keyframes hold DELTAS FROM REST as [angle, offset_x, offset_y].',
    '# frames between keys interpolate linearly; animations that overlap on a',
    '# bone add, so composition order does not matter. a forward loop wraps from',
    '# its last key to frame 0; back-and-forth reverses at its last frame.',
    'bones:',
  ];
  if (!doc.bones.length) out[out.length - 1] = 'bones: []';

  for (const b of doc.bones) {
    const f = frames.get(boneKey(b.id, 'root'));
    if (!f) continue;
    out.push(`  - id: ${b.id}`);
    out.push(`    name: ${JSON.stringify(b.name)}`);
    out.push(`    parent: ${b.ref?.bone ?? 'null'}`);
    if (b.ref?.bone) out.push(`    parent_end: ${b.ref.end ?? 'root'}`);
    out.push(`    pos: [${fmt(f.pos.x, 3)}, ${fmt(f.pos.y, 3)}]`);
    out.push(`    angle: ${fmt(wrapDeg(f.angle), 3)}`);
    out.push(`    length: ${fmt(b.length, 3)}`);
    if (isPoint(b)) out.push('    attachment: true');
  }

  // art is emitted in PAINT order, back to front, so the engine draws the list
  // as it reads it -- no sorting, no z field to get backwards. that is the
  // reverse of the tool's list, where index 0 is nearest the viewer.
  //
  // the file is referenced by name, not inlined: the engine loads its own
  // assets, and two items sharing a file should cost one load and two draws.
  const art = [...(doc.art ?? [])].reverse();
  out.push(art.length ? 'art:' : 'art: []');
  for (const a of art) {
    out.push(`  - id: ${a.id}`);
    out.push(`    name: ${JSON.stringify(a.name)}`);
    // the bundle may rename a file to keep two items with different anchors
    // apart, so reference what was actually written
    out.push(`    svg: ${JSON.stringify(artPaths?.get(a.id) ?? a.filename)}`);
    // where the art hangs: a bone (root or tip), or another art's anchor
    if (a.ref?.art != null) {
      out.push(`    parent_art: ${a.ref.art}`);
      out.push(`    parent_anchor: ${JSON.stringify(a.ref.anchor)}`);
    } else {
      out.push(`    parent: ${a.ref?.bone ?? 'null'}`);
      if (a.ref?.bone) out.push(`    parent_end: ${a.ref.end ?? 'root'}`);
    }
    out.push(`    offset: [${fmt(a.offset.x, 3)}, ${fmt(a.offset.y, 3)}]`);
    out.push(`    angle: ${fmt(wrapDeg(a.angle), 3)}`);
    if (a.scale !== 1) out.push(`    scale: ${fmt(a.scale, 4)}`);
    if (!a.visible) out.push('    visible: false');
  }

  const anims = doc.animations ?? [];
  out.push(anims.length ? 'animations:' : 'animations: []');
  for (const anim of anims) {
    out.push(`  - id: ${anim.id}`);
    out.push(`    name: ${JSON.stringify(anim.name)}`);
    out.push(`    type: ${anim.type}`);
    out.push(`    length: ${anim.length}`);
    out.push(anim.keyframes.length ? '    keyframes:' : '    keyframes: []');
    for (const kf of anim.keyframes) {
      out.push(`      - frame: ${kf.frame}`);
      const entries = Object.entries(kf.deltas);
      if (entries.length) {
        out.push('        deltas:');
        for (const [boneId, d] of entries) {
          out.push(`          ${boneId}: [${fmt(d.angle, 3)}, ${fmt(d.offsetX, 3)}, ${fmt(d.offsetY, 3)}]`);
        }
      } else {
        out.push('        deltas: {}');
      }
    }
  }

  return out.join('\n') + '\n';
}

// stamp the schema, exactly as persisting to localStorage does. without it the
// file fails its own version check on the way back in.
export const exportJson = (doc) =>
  JSON.stringify({ ...doc, version: SCHEMA }, null, 2);

export function importJson(text) {
  const raw = JSON.parse(text);
  if (!Array.isArray(raw?.bones)) throw new Error('not a rigger document');
  // same gate as localStorage: a file from an older schema is rejected loudly
  // rather than crashing the resolver on a missing field
  // normalizeDoc migrates anything from MIN_SCHEMA up, and throws a
  // SchemaError with a reason for anything it genuinely cannot bring forward
  const doc = normalizeDoc(raw);
  if (!doc) throw new Error('not a rigger document');
  return doc;
}

export function download(filename, text, type = 'text/plain') {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.append(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
